
import { authOptions } from "@/app/api/auth/[...nextauth]/options";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import USidebar from "@/components/USidebar";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  
  return (
    session ? (
      <div className="bg-slate-900 px-24 flex min-h-screen justify-self-center items-start">
        {/* <SidebarProvider> */}
        <div className="flex flex-row w-full mx-auto p-5 items-start mt-10">
          <USidebar />
          <div className="flex-1 bg-gray-900 p-6 rounded-lg">
            {children}
          </div>
        </div>
        {/* </SidebarProvider> */}
      </div>
    ) : null
  )
}


// <div className="bg-slate-900 flex min-h-screen "
//     >
//         <div className="flex justify-stretch items-start p-5">
//       <SidebarProvider>

//           {/* <div> */}
//             <USidebar />
//           {/* </div> */}

//           <div>
//             {/* <SidebarTrigger /> */}
//             {children}
//           </div>
//       </SidebarProvider>
//         </div>

//     </div>
